spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: provider-user
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    hikari:
      minimum-idle: 30
      idle-timeout: 600000
      maximum-pool-size: 600
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

server:
  port: 11000

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

mybatis:
  type-aliases-package: net.p5w.provider.domain
  mapper-locations: classpath:mapper/*.xml