spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-zuul-business

server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

zuul:
  routes:
    api-business-admin:
      # 以 /api/consumer/ 开头的请求都转发给 consumer-user 服务
      path: /api/consumer/**
      serviceId: consumer-user