spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: consumer-user

server:
  port: 12000

eureka:
  instance:
    hostname: localhost
    # 增加用于集群的配置，集群名为 business，与 Turbine 的配置匹配
    metadata-map:
      cluster: consumer
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

feign:
  hystrix:
    enabled: true